- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.after_install.sh:
    ~/.bash_profile:
      force: true
    ~/.bashrc:
      force: true
    ~/.config:
      force: true
    ~/.fzf:
      force: true
    ~/.gitconfig:
      force: true
    ~/.inputrc:
    ~/.oh-my-zsh:
      force: true
    ~/.requirements.txt:
    ~/.shell:
    ~/.tmux.conf:
      force: true
    ~/.vim:
      force: true
    ~/.vimrc:
      force: true
    ~/.zshrc:
      force: true
    ~/.rbenv:

- shell:
  - git submodule sync --recursive
  - git update-submodules
  - command -v python3 || apt install -y python3 
  - command -v pip3 || apt install -y python3-pip
  - PREFIX=~/.ruby-build ~/.rbenv/plugins/ruby-build/install.sh
